theme = "default"
client_id = "cdc7865d13de4b8a91f7e542dfe3cf71"
client_port = 8080
playback_format = """
{track} • {artists}
{album}
{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
playback_window_position = "Top"
cover_img_length = 24
cover_img_width = 12
playback_window_width = 6
enable_media_control = true
enable_streaming = "Always"
enable_notify = true
enable_cover_image_cache = true
default_device = "spotify-player"
notify_streaming_only = false
# NixOS hook
player_event_hook_command = { command = ".config/spotify-player/nix-spotify-player.sh", args = [] }
# Regular hook
# player_event_hook_command = { command = ".config/spotify-player/spotify-player.sh", args = [] }

[copy_command]
command = "wl-copy"

[notify_format]
summary = "{track} • {artists}"
body = "{album}"

[device]
name = "spotify-player"
device_type = "Computer"
volume = 70
bitrate = 320
audio_cache = false 
normalization = false
